// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmtN9rOXH7_OHBibsGyHwj6MM8g3TI71A',
    appId: '1:21329661514:web:7d4d10bc4bae3fd52b60b3',
    messagingSenderId: '21329661514',
    projectId: 'to-do-list-app-837a0',
    authDomain: 'to-do-list-app-837a0.firebaseapp.com',
    storageBucket: 'to-do-list-app-837a0.firebasestorage.app',
    measurementId: 'G-49WC443H9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLcRnIlbPfThQ1Peg2SZNltC11UGsMfk',
    appId: '1:21329661514:android:5a71c9583e84514b2b60b3',
    messagingSenderId: '21329661514',
    projectId: 'to-do-list-app-837a0',
    storageBucket: 'to-do-list-app-837a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTRZpyOJPDJ7uiV44h29jRiMHfNFvY0xI',
    appId: '1:21329661514:ios:20778ec46d755c692b60b3',
    messagingSenderId: '21329661514',
    projectId: 'to-do-list-app-837a0',
    storageBucket: 'to-do-list-app-837a0.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTRZpyOJPDJ7uiV44h29jRiMHfNFvY0xI',
    appId: '1:21329661514:ios:20778ec46d755c692b60b3',
    messagingSenderId: '21329661514',
    projectId: 'to-do-list-app-837a0',
    storageBucket: 'to-do-list-app-837a0.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmtN9rOXH7_OHBibsGyHwj6MM8g3TI71A',
    appId: '1:21329661514:web:c8fc60640655e0fc2b60b3',
    messagingSenderId: '21329661514',
    projectId: 'to-do-list-app-837a0',
    authDomain: 'to-do-list-app-837a0.firebaseapp.com',
    storageBucket: 'to-do-list-app-837a0.firebasestorage.app',
    measurementId: 'G-ZPHHRG49WR',
  );
}
